### ISSUE TITLE
bot's current status

### ISSUE THREAD

**Issue by k1ck3r** [KararTY/DiscordTwitchAnnouncer#14]
hey again ;)

not really big issue, but i've got additional module included which sets bot's status (ex. DND/Online/Away - not the Rich Presence thing) and once your bot loads, it's temporary sets the status to Online. Then again, if i switch the announcer off, the activity is properly changed.

any idea what might causes it?

**Comment by KararTY** [comment]
I'm not sure what you're referring to.
What additional module?

Could you show an image of the issue?

**Comment by k1ck3r** [comment]
yeah i maybe didn't express my self quite well :)

here is the image https://imgur.com/a/Cuwe4ff and it's really not-so-important 'issue' - using some custom rich presences for the bot, but it's activity shouldn't be "Online" as indicates it on the screenshot. in your script i just have require ./some.js which actually does the "Do not Disturb" and "Away" activity.

anyhow thanks a lot for your prompt reply

**Comment by k1ck3r** [comment]
i'm sorry to announce a bad news, but both ways doesn't work and produce the following error related with the value of bot's status 
```

Logged into Discord.
(node:19305) UnhandledPromiseRejectionWarning: TypeError: Status must be a string
    at resolve (/home/golemetz/golemetz/node_modules/discord.js/src/structures/ClientUser.js:208:52)
    at new Promise (<anonymous>)
    at ClientUser.setPresence (/home/golemetz/golemetz/node_modules/discord.js/src/structures/ClientUser.js:194:12)
    at ClientUser.setStatus (/home/golemetz/golemetz/node_modules/discord.js/src/structures/ClientUser.js:265:17)
    at Client.client.once (/home/golemetz/golemetz/twitch.js:474:21)
    at Object.onceWrapper (events.js:286:20)
    at Client.emit (events.js:203:15)
    at WebSocketConnection.triggerReady (/home/golemetz/golemetz/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:125:17)
    at WebSocketConnection.checkIfReady (/home/golemetz/golemetz/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:141:61)
    at GuildCreateHandler.handle (/home/golemetz/golemetz/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
(node:19305) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19305) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by KararTY** [comment]
I don't recognize `twitch.js`. Is that `app.js` but renamed? Or is that your script?

If it's your script, would you mind sharing the relevant snippet of code?
It looks like your setStatus(<content>) isn't a string.

It should look like this.
```js
client.user.setStatus('online')
// 'online' | 'idle' | 'dnd' | 'invisible'
```

And, dismiss the whole putting the require on that line.

Also man, don't worry. I'd like my stuff to work, is all.

**Comment by k1ck3r** [comment]
seems my reply wasn't arrived last night. as your previous comment, everything went smooth and working as intended with the hard coded status in mind ;)

appreciate your help <3
